//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int Pj_ID { get; set; }
        public string Pj_StuID { get; set; }
        public string Pj_TeaID { get; set; }
        public string Pj_NameTH { get; set; }
        public string Pj_NameENG { get; set; }
        public System.DateTime Pj_Date { get; set; }
        public string Pj_TypePj { get; set; }
        public string Pj_File { get; set; }
        public string Pj_Github { get; set; }
        public string Pj_Description { get; set; }
        public string Pj_Linkweb { get; set; }
        public string Pj_Video { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
