//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CESup
    {
        public string CESUB_No { get; set; }
        public string CESUB_Name { get; set; }
        public Nullable<int> CESUB_Statud { get; set; }
        public string CE_No { get; set; }
    
        public virtual ComputerEquipment ComputerEquipment { get; set; }
    }
}
