//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CESup
    {
        public int CESUB_ATNO { get; set; }
        public string CESUB_NO { get; set; }
        public string CESUB_Name { get; set; }
        public Nullable<int> CESUB_Status { get; set; }
        public Nullable<int> CE_ATNO { get; set; }
    }
}
