//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerEquipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComputerEquipment()
        {
            this.CESups = new HashSet<CESup>();
            this.Disposes = new HashSet<Dispose>();
        }
    
        public string CE_No { get; set; }
        public Nullable<System.DateTime> CE_DateIN { get; set; }
        public string CE_Name { get; set; }
        public string CE_Noce { get; set; }
        public Nullable<int> CE_Piece { get; set; }
        public Nullable<double> CE_Price { get; set; }
        public Nullable<double> CE_PriceTotal { get; set; }
        public string CE_TeaID { get; set; }
        public string CE_Budget { get; set; }
        public Nullable<int> CE_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CESup> CESups { get; set; }
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dispose> Disposes { get; set; }
    }
}
