//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_Details
    {
        public int Gen_ID { get; set; }
        public string Gen_Name { get; set; }
        public Nullable<System.DateTime> Gen_Date { get; set; }
        public string Gen_Location { get; set; }
        public Nullable<int> Gen_Status { get; set; }
        public Nullable<int> Gen_NO { get; set; }
    
        public virtual Gen_Status Gen_Status1 { get; set; }
        public virtual Generation Generation { get; set; }
    }
}
