//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Generation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Generation()
        {
            this.Applieds = new HashSet<Applied>();
            this.Gen_Details1 = new HashSet<Gen_Details>();
        }
    
        public int Gen_NO { get; set; }
        public Nullable<int> Gen_SCID { get; set; }
        public string Gen_Name { get; set; }
        public Nullable<int> Gen_Member { get; set; }
        public Nullable<int> Gen_MemberMax { get; set; }
        public string Gen_Details { get; set; }
        public string Gen_Year { get; set; }
        public Nullable<double> Gen_Fee { get; set; }
        public string Gen_TextForMail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applied> Applieds { get; set; }
        public virtual Short_Course Short_Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Details> Gen_Details1 { get; set; }
    }
}
