//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int HIS_ID { get; set; }
        public string HIS_StuID { get; set; }
        public Nullable<int> HIS_Job { get; set; }
        public string HIS_Jobname { get; set; }
        public Nullable<System.DateTime> HIS_Year { get; set; }
        public string HIS_Company { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Student Student { get; set; }
    }
}
