//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CsManagementEntities : DbContext
    {
        public CsManagementEntities()
            : base("name=CsManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applied> Applieds { get; set; }
        public virtual DbSet<CESup> CESups { get; set; }
        public virtual DbSet<ComputerEquipment> ComputerEquipments { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Dispose> Disposes { get; set; }
        public virtual DbSet<Gen_Status> Gen_Status { get; set; }
        public virtual DbSet<Generation> Generations { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<HitCount> HitCounts { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Register_SC> Register_SC { get; set; }
        public virtual DbSet<RegisterLink> RegisterLinks { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<Short_Course> Short_Course { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Syllabu> Syllabus { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<ProjectView> ProjectViews { get; set; }
        public virtual DbSet<Totaljob> Totaljobs { get; set; }
        public virtual DbSet<TotalSchool> TotalSchools { get; set; }
    }
}
