//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int New_ID { get; set; }
        public string New_Name { get; set; }
        public string New_Details { get; set; }
        public string New_Img { get; set; }
        public Nullable<System.DateTime> New_Date { get; set; }
    }
}
