//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectView
    {
        public int Pj_ID { get; set; }
        public string Pj_StuID { get; set; }
        public string Pj_NameTH { get; set; }
        public string Pj_File { get; set; }
        public string Pj_Linkweb { get; set; }
        public string Pj_Video { get; set; }
        public Nullable<int> Pj_Rate { get; set; }
        public string Stu_Name { get; set; }
        public string Stu_Surname { get; set; }
        public string Stu_Img { get; set; }
    }
}
