//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Stu_Pro = new HashSet<Stu_Pro>();
            this.Tea_Pro = new HashSet<Tea_Pro>();
        }
    
        public int Pj_ID { get; set; }
        public string Pj_StuID { get; set; }
        public string Pj_TeaID { get; set; }
        public string Pj_NameTH { get; set; }
        public string Pj_NameENG { get; set; }
        public System.DateTime Pj_Date { get; set; }
        public string Pj_TypePj { get; set; }
        public string Pj_File { get; set; }
        public string Pj_Github { get; set; }
        public string Pj_Description { get; set; }
        public string Pj_Linkweb { get; set; }
        public string Pj_Video { get; set; }
        public Nullable<int> Pj_Rate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stu_Pro> Stu_Pro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tea_Pro> Tea_Pro { get; set; }
    }
}
