//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Histories = new HashSet<History>();
            this.Projects = new HashSet<Project>();
        }
    
        public string Stu_ID { get; set; }
        public string Stu_Title { get; set; }
        public string Stu_Name { get; set; }
        public string Stu_Surname { get; set; }
        public Nullable<bool> Stu_Sex { get; set; }
        public Nullable<System.DateTime> Stu_Birthday { get; set; }
        public string Stu_Email { get; set; }
        public string Stu_Tel { get; set; }
        public string Stu_Address { get; set; }
        public Nullable<int> Stu_School { get; set; }
        public string Stu_OldEdu { get; set; }
        public string Stu_Img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> Histories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects { get; set; }
        public virtual School School { get; set; }
    }
}
