//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Syllabu
    {
        public int Sy_ID { get; set; }
        public string Sy_Name { get; set; }
        public string Sy_Details { get; set; }
        public string Sy_Img { get; set; }
    }
}
