//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tea_Pro
    {
        public int ID { get; set; }
        public string Teac_ID { get; set; }
        public Nullable<int> Pro_ID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
